databases:
  - name: tutor2026-db
    plan: free

services:
  - type: web
    name: tutor-votacao-2026
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tutor2026-db
          property: connectionString
      - key: ADMIN_PASSWORD
        value: "1243##"
      - key: SECRET_KEY
        value: "Xc_Xx0ajPns7-VLIXNOZeE3hF0mfFjF6vSD6gOzSVSw"
